name: 'Deploy Configuration'
description: 'Uses medic-conf to deploy a CHT configuration'
inputs:
  directory:
    required: true
    default: '.'
  hostname:
    required: true
  username:
    required: true
    default: 'medic'
  password:
    required: true
runs:
  using: 'ubuntu-latest'
  steps:
  - run: |
        npm ci
        pip install --user -U pip
        sudo python -m pip install git+https://github.com/medic/pyxform.git@medic-conf-1.17#egg=pyxform-medic
    shell: bash
    working-directory: ${{ inputs.directory }}
  - run: npx medic-conf --url=https://${{ inputs.username }}:${{ inputs.password }}@${{ inputs.hostname }} compile-app-settings convert-app-forms convert-collect-forms convert-contact-forms upload-app-settings upload-app-forms upload-collect-forms upload-contact-forms upload-resources upload-custom-translations --force
    shell: bash
    working-directory: ${{ inputs.directory }}
