name: Deploy configurations via medic-conf

on:
  push:
    branches: [ master ]
#     paths:
#     - 'ebs_with_tracing/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: install prerequisites
      run: |
        npm ci
        pip install --user -U pip
        sudo python -m pip install git+https://github.com/medic/pyxform.git@medic-conf-1.17#egg=pyxform-medic
      working-directory: ./ebs_with_tracing
    - name: medic-conf deployment
      run: npx medic-conf --url=https://admin:pass@031c0c650801.ngrok.io/ compile-app-settings convert-app-forms convert-collect-forms convert-contact-forms upload-app-settings upload-app-forms upload-collect-forms upload-contact-forms upload-resources upload-custom-translations --force
      working-directory: ./ebs_with_tracing
