name: Deploy configurations via medic-conf

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        directory: ['./ebs_with_tracing']

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - uses: 'actions/deploy-with-medic-conf'
      with:
        directory: ${{ matrix.directory }}
        hostname: 031c0c650801.ngrok.io
        username: admin
        password: pass
