name: Deploy configurations via medic-conf

on:
  push:
    branches: [ master ]
#     paths:
#     - 'ebs_with_tracing/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - working-directory: ./ebs_with_tracing
    - run: |
        npm ci
        npx medic-conf --url=https://admin:pass@031c0c650801.ngrok.io/ --force compile-app-settings convert-app-forms convert-collect-forms convert-contact-forms upload-app-settings upload-app-forms upload-collect-forms upload-contact-forms upload-resources upload-custom-translations
